### ISSUE TITLE
PermissionError on sending Arping as non-root uid 1001

### ISSUE THREAD

**Issue by Cellebyte** [bitnami/bitnami-docker-metallb-speaker#1]
**Description**

I used the image with my helm chart. I proposed here: https://github.com/bitnami/charts/pull/2068

The image runs under the following `securityContext` as a `DaemonSet`.
```yaml
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
```

**Steps to reproduce the issue:**

1. helm install metallb bitnami/metallb
2. kubectl logs -f metallb-speaker-\<uid\>

**Describe the results you received:**
```txt
{"caller":"announcer.go:99","error":"creating ARP responder for \"ens192\": operation not permitted","interface":"ens192","msg":"failed to create ARP responder","op":"createARPResponder","ts":"2020-04-01T09:03:24.601968041Z"}
```

**Describe the results you expected:**

```txt
{"caller":"announcer.go:103","event":"createARPResponder","interface":"ens192","msg":"created ARP responder for interface","ts":"2020-04-01T09:04:28.681882839Z"}
{"caller":"announcer.go:112","event":"createNDPResponder","interface":"ens192","msg":"created NDP responder for interface","ts":"2020-04-01T09:04:28.683076994Z"}
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes 1.17.1
